version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "httpx"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
